# -*- coding: utf-8 -*-
"""tarea 2 simulacion .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewpJ7r7ctCFXf4QytyLN9f_m4ZNSquhJ
"""

import numpy as np
import time
from numba import prange, njit, set_num_threads

N = 1_000_000 #number of random points

pi = 6*np.arcsin(1/2) #proposed def. of pi
set_num_threads(2) #number of threads to use

@njit(parallel=True) #parallelized computation of pi
def pnt(N):
    I = 0 #counter of points inside the unitary circle
    for i in prange(N): #parallel range
        x = 2*np.random.random()-1 #rndm coordinates generated in (-1,1)
        y = 2*np.random.random()-1
        if x**2 +y**2 <=1: # condition to satisfy if the point is inside
            I += 1
    return I

t1 = time.time() #time setup
pi_est = 4*pnt(N)/N #estimate of pi
t2 = time.time()

#printing the results
print(f"estimate of pi: {pi_est}")
print(f"relative error: {np.abs(100*(pi_est-pi)/pi)}")
print(f"time taken: {t2-t1}")

